### ISSUE TITLE
Login Issues - Twitter and Email

### ISSUE THREAD

**Issue by regrounding** [jliphard/CancerBase#38]
I still (again?) can't login with Twitter:

So now I can't recall HOW I logged inn/joined and notice that if I joined by email (which is what I think I resorted to, having 2 FB accounts), and there is no way to retrieve user name/password. I'm officially in there twice now. 

Trying to login with Twitter, I get this:

Failed to find request token in session

Error: Failed to find request token in session
    at SessionStore.get (/var/lib/js/CancerBase/node_modules/passport-oauth1/lib/requesttoken/session.js:13:44)
    at Strategy.OAuthStrategy.authenticate (/var/lib/js/CancerBase/node_modules/passport-oauth1/lib/strategy.js:214:33)
    at Strategy.authenticate (/var/lib/js/CancerBase/node_modules/passport-twitter/lib/strategy.js:87:40)
    at attempt (/var/lib/js/CancerBase/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (/var/lib/js/CancerBase/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (/var/lib/js/CancerBase/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/lib/js/CancerBase/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/var/lib/js/CancerBase/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/lib/js/CancerBase/node_modules/express/lib/router/layer.js:95:5)
    at /var/lib/js/CancerBase/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/var/lib/js/CancerBase/node_modules/express/lib/router/index.js:330:12)
    at next (/var/lib/js/CancerBase/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/var/lib/js/CancerBase/node_modules/express/lib/router/index.js:176:3)
    at router (/var/lib/js/CancerBase/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/var/lib/js/CancerBase/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/js/CancerBase/node_modules/express/lib/router/index.js:312:13)

**Comment by ebcopur** [comment]
The twitter issue should now be resolved I believe. Will look into creating a password recovery module in a separate issue, this one can be closed.
